apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.annotations.group }}
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.label }}
status:
  loadBalancer: {}
