apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.annotations.group }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.webport }}
    protocol: TCP
    targetPort: 80
  - port: {{ .Values.service.sshport }}
    protocol: TCP
    targetPort: 22
  selector:
    app: {{ .Chart.Name }}
status:
  loadBalancer: {}
